version: '3.8'

services:

  mickey-1337:
    build: .
    ports:
        - 1337:1337
    read_only: true
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus:   2
          memory: 128M
          pids:   1000
        reservations:
          cpus:   0.5
          memory: 64M